builds:
  - binary: git-version-next
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  tap:
    owner: kazeburo
    name: git-version-next
brews:
  - description: "increments version (git tag) numbers simply"
    github:
      owner: kazeburo
      name: homebrew-tap
    homepage: "https://github.com/kazeburo/git-version-next"
    install: |
      bin.install "git-version-next"